---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: borealis
description: This is my personal OS image.
alt-tags:
  - stable
  - stable-weekly
base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable

# Executed in order
modules:
  - from-file: modules/init.yml
  # - from-file: modules/overrides.yml      # Curently not used
  # - from-file: modules/origin-flatpak.yml # Under construction
  - from-file: modules/custom-flatpak.yml
  - from-file: modules/custom-rpm.yml
  - from-file: modules/crossover.yml
  - from-file: modules/chezmoi.yml
  - from-file: modules/bling.yml
  - type: signing









